### ISSUE TITLE
Admin regions don't have their name properties

### ISSUE THREAD

**Issue by gingemonster** [mapbox/mapbox-studio-outdoors.tm2#4]
At the moment this style, and all others as far as I can see, have an "admin" layer but it does not have the OSM name for that admin area so we cannot add labels for regions but we can draw their boundaries.

This would be really nice to be able to have access to even if the default style doesn't reference it

**Comment by ajashton** [comment]
In Mapbox vector tiles, layers for labeling are separate from layers for drawing lines and polygons. Use the `#admin` layer for styling the boundary lines, and the `#country_label` and `#state_label` layers for labeling them.

We do not include labels for all administrative regions, however. We may add more in the future, but if you need these now you can add them via a custom layer with data from Natural Earth or OSM. See this guide: https://www.mapbox.com/mapbox-studio/source-quickstart/
