### ISSUE TITLE
natural=peak labels?

### ISSUE THREAD

**Issue by jstratman** [mapbox/mapbox-studio-outdoors.tm2#5]
We don't currently label peaks on our core terrain map. That was one of the complaints by a user, and it struck me as a valid (if minor) complaint. We do label these on the run/bike/hike map. 

Virtually every topo or terrain map has this, and they are already in OSM data as natural=peak. Something to consider for future enhancement! 

If this isn't the right place to post this issue, let me know. Also, if this was a deliberate design choice, please shut this ticket down. 

Terrain V2: 
![image](https://cloud.githubusercontent.com/assets/12281722/9239108/8a8f7964-410d-11e5-8afa-9587e147e7ef.png)

Run/Bike/Hike:
![image](https://cloud.githubusercontent.com/assets/12281722/9239134/be79c4e6-410d-11e5-9b25-5e4089d5b0bf.png)

**Comment by ajashton** [comment]
Unintentional oversight. I'll make sure these get added.
